on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo test

  deploy:
    if: ${{ github.ref == 'ref/head/master' }}
    runs-on: ubuntu-latest
    needs: [test]
    steps:
        - run: echo deploy
