name: Test PRs

on:
  push:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name != 'pull_request' || github.event.label.name == 'test')
    steps:
      - run: echo test ${{ github.ref }}
